'use strict';

module.exports = {
  admin: {
    type: 'admin',
    routes: [
      {
        method: 'GET',
        path: '/overview',
        handler: 'dashboard.overview',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/pending-comments',
        handler: 'dashboard.pendingComments',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/pending-comments/:id/approve',
        handler: 'dashboard.approveComment',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/pending-comments/:id/reject',
        handler: 'dashboard.rejectComment',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/customers',
        handler: 'dashboard.customers',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/test-sms',
        handler: 'dashboard.testSms',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/payment-settings',
        handler: 'payment.getSettings',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'PUT',
        path: '/payment-settings',
        handler: 'payment.updateSettings',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/payment-settings/test-connection',
        handler: 'payment.testConnection',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/payment-settings/go-live-checklist',
        handler: 'payment.goLiveChecklist',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/sms-settings',
        handler: 'sms.getSettings',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'PUT',
        path: '/sms-settings',
        handler: 'sms.updateSettings',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/sms-settings/test-connection',
        handler: 'sms.testConnection',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/sms-settings/test-event',
        handler: 'sms.testEvent',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/sms-settings/test-all',
        handler: 'sms.testAll',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/sms-settings/go-live-checklist',
        handler: 'sms.goLiveChecklist',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/payments',
        handler: 'payment.listPayments',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/payments/:id',
        handler: 'payment.getPayment',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/payments/:id/refund',
        handler: 'payment.refundPayment',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/orders/:id/mark-paid',
        handler: 'payment.markOrderPaid',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/orders/:id/mark-failed',
        handler: 'payment.markOrderFailed',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/test-payment-notification',
        handler: 'payment.testPaymentNotification',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/products',
        handler: 'product.list',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/products/category-options',
        handler: 'product.categoryOptions',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/products/:id',
        handler: 'product.findOne',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/products',
        handler: 'product.create',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'PUT',
        path: '/products/:id',
        handler: 'product.update',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'DELETE',
        path: '/products/:id',
        handler: 'product.remove',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/products/:id/publish',
        handler: 'product.publish',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/categories',
        handler: 'category.list',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/categories/parent-options',
        handler: 'category.parentOptions',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'GET',
        path: '/categories/:id',
        handler: 'category.findOne',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'POST',
        path: '/categories',
        handler: 'category.create',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'PUT',
        path: '/categories/:id',
        handler: 'category.update',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
      {
        method: 'DELETE',
        path: '/categories/:id',
        handler: 'category.remove',
        config: { policies: ['admin::isAuthenticatedAdmin'] },
      },
    ],
  },
};
